<?xml version="1.0"?>
<robot name="popcanbot" xmlns:xacro="http://wiki.ros.org/xacro">

<xacro:property name="car_length" value="0.609"/>
<xacro:property name="car_width" value="0.5"/>
<xacro:property name="car_height" value="0.05"/>
<xacro:property name="clearance" value="0.10"/>
<xacro:property name="wheel_separation" value="0.56"/>
<xacro:property name="wheel_width" value="0.025"/>
<xacro:property name="wheel_radius" value="0.07"/>
<xacro:property name="caster_wheel_radius" value="0.04"/>
<xacro:property name="use_camera" value="true"/>

<xacro:property name="gripper_left_lower_lim" value="-0.5"/>
<xacro:property name="gripper_left_upper_lim" value="0.0"/>
<xacro:property name="gripper_right_lower_lim" value="-0.5"/>
<xacro:property name="gripper_right_upper_lim" value="0.0"/>
<!-- TODO(lwalter) pass these in as args -->

<xacro:include filename="$(find popcanbot_description)/urdf/popcanbot.gazebo"/>
<xacro:include filename="$(find popcanbot_description)/urdf/util.xacro"/>

  <link name="base_link"/>
  <xacro:block name="chassis_link" length="${car_length}"
      width="${car_width}" height="${car_height}" mass="10.0"
      r="0.8" g="0.7" b="0.1"/>
  <joint name="chassis_joint" type="fixed">
    <parent link="base_link"/>
    <child link="chassis_link"/>
    <origin xyz="${-car_length/2 + 0.05} 0 0" rpy="0 0 0"/>
  </joint>

  <!-- every link has to have inertia in order for it to work in gazebo
    even if it just connects two inertia links- without it the child link
    that doesn't have inertia won't appear.
    -->
  <xacro:block name="caster_block" length="${0.03}"
      width="${0.03}" height="${0.03}" mass="0.1"/>
  <joint name="caster_joint" type="continuous">
    <parent link="base_link"/>
    <child link="caster_block"/>
    <axis xyz="0 0 1"/>
    <origin xyz="${-car_length + 0.1} 0 ${-car_height/2}" rpy="0 0 0"/>
  </joint>
  <xacro:generic_wheel name="wheel_caster" parent="caster_block"
      width="${wheel_width}"
      radius="${caster_wheel_radius}" mass="0.1" use_tran="false"
      x="0.02"
      z="${-(clearance - caster_wheel_radius)}"
      mu1="20" mu2="10"/>

  <xacro:block name="main_axle" length="${car_width/8.0}"
      width="${car_width + 0.05}" height="${car_width/8.0}" mass="0.1"
      />
  <joint name="main_axle_joint" type="fixed">
    <parent link="base_link"/>
    <child link="main_axle"/>
    <origin xyz="0 0 ${-(car_height/2 + clearance - wheel_radius)}"
        rpy="0 0 0"/>
  </joint>

  <xacro:generic_wheel name="wheel_front_left" parent="main_axle"
      y="${wheel_separation/2}"
      width="${wheel_width}" radius="${wheel_radius}"
      use_tran="false"/>
  <xacro:generic_wheel name="wheel_front_right" parent="main_axle"
      y="${-wheel_separation/2}"
      width="${wheel_width}" radius="${wheel_radius}"
      y_axis="1" use_tran="false"/>

  <!-- the arm -->
  <xacro:block name="arm_vertical" length="0.05"
      width="0.05" height="0.5" mass="1.0" z="0.25"/>
  <joint name="arm_vertical_rotary_joint" type="revolute">
    <parent link="base_link"/>
    <child link="arm_vertical"/>
    <origin xyz="${-car_length/3} 0 ${car_height/4}" rpy="0 0 0"/>
    <axis xyz="0 0 -1"/>
    <limit effort="100.0" upper="1.6" lower="-1.6" velocity="0.5"/>
    <dynamics damping="0.1" friction="0.1"/>
  </joint>

  <transmission name="arm_vertical_rotary_tran">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="arm_vertical_rotary_joint">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="arm_vertical_rotary_motor">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <xacro:block name="arm_vertical_platform" length="0.05"
      width="0.1" height="0.05" mass="0.1"
      r="0.8" g="0.8" b="0.8"/>
  <joint name="arm_vertical_platform_joint" type="prismatic">
    <parent link="arm_vertical"/>
    <child link="arm_vertical_platform"/>
    <origin xyz="0.05 0 0.25" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="20.0" velocity="0.25" lower="-0.14" upper="0.35"/>
    <dynamics damping="0.1" friction="0.1"/>
  </joint>
  <transmission name="arm_vertical_rotary_tran">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="arm_vertical_platform_joint">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="arm_vertical_platform_motor">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <xacro:block name="arm_horizontal" length="0.5"
      width="0.05" height="0.05" mass="0.2"/>
  <joint name="arm_horizontal_platform_joint" type="prismatic">
    <parent link="arm_vertical_platform"/>
    <child link="arm_horizontal"/>
    <origin xyz="0.1 -0.06 -0.05" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit effort="20.0" velocity="0.25" lower="-0.22" upper="0.05"/>
    <dynamics damping="0.1" friction="0.1"/>
  </joint>
  <transmission name="arm_vertical_rotary_tran">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="arm_horizontal_platform_joint">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="arm_horizontal_platform_motor">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <!-- gripper -->
  <xacro:macro name="gripper" params="name parent x y z roll pitch yaw ax ay az lower_lim upper_lim">
  <xacro:block name="${name}" length="0.04"
      width="0.02" height="0.02" mass="0.05" r="0.1" b="0.1" g="0.6" x="0.03"
      mu="1.0"/>
  <joint name="${name}_joint" type="revolute">
    <parent link="${parent}"/>
    <child link="${name}"/>
    <origin xyz="${x} ${y} ${z}" rpy="${roll} ${pitch} ${yaw}"/>
    <axis xyz="${ax} ${ay} ${az}"/>
    <limit effort="200.0" upper="${upper_lim}" lower="${lower_lim}" velocity="0.5"/>
    <dynamics damping="0.1" friction="0.1"/>
  </joint>
  <xacro:block name="${name}_mid1" length="0.04"
      width="0.02" height="0.02" mass="0.05" r="0.1" b="0.1" g="0.6" x="0.03"
      mu="1.0"/>
  <joint name="${name}_mid1_joint" type="fixed">
    <parent link="${name}"/>
    <child link="${name}_mid1"/>
    <origin xyz="0.03 0.0 0.0" rpy="0 0 -0.28"/>
  </joint>
  <xacro:block name="${name}_mid2" length="0.04"
      width="0.02" height="0.02" mass="0.05" r="0.1" b="0.1" g="0.6" x="0.03"
      mu="1.0"/>
  <joint name="${name}_mid2_joint" type="fixed">
    <parent link="${name}_mid1"/>
    <child link="${name}_mid2"/>
    <origin xyz="0.03 0.0 0.0" rpy="0 0 -0.28"/>
  </joint>

  <xacro:block name="${name}_tip" length="0.04"
      width="0.02" height="0.02" mass="0.05" r="0.1" b="0.1" g="0.6" x="0.03"
      mu="1.0"/>
  <joint name="${name}_tip_joint" type="fixed">
    <parent link="${name}_mid2"/>
    <child link="${name}_tip"/>
    <origin xyz="0.03 0.0 0.0" rpy="0 0 -0.28"/>
  </joint>

  <transmission name="${name}_rotary_tran">
>>>>>>> 5e5cc29bd81872f5302f9bae12d8c56d68755a0e
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="${name}_joint">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="${name}_motor">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  </xacro:macro>

  <xacro:gripper name="gripper_left"
      parent="arm_horizontal"
      x="0.25" y="0.013" z="-0.1"
      roll="0" pitch="0" yaw="0.9"
      ax="0" ay="0" az="1"
      lower_lim="${gripper_left_lower_lim}" upper_lim="${gripper_left_upper_lim}"/>
  <xacro:gripper name="gripper_right"
      parent="arm_horizontal"
      x="0.25" y="-0.013" z="-0.1"
      roll="${pi}" pitch="0" yaw="-0.9"
      ax="0" ay="0" az="1"
      lower_lim="${gripper_right_lower_lim}" upper_lim="${gripper_right_upper_lim}"/>

  <!-- sensors -->
  <xacro:if value="${use_camera}">
  <xacro:block name="camera_mast" length="0.04"
      width="0.02" height="0.03" mass="0.1"/>
  <joint name="camera_mast_joint" type="prismatic">
    <parent link="arm_horizontal"/>
    <child link="camera_mast"/>
    <origin xyz="0.1 0 0.2" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="20.0" velocity="0.25" lower="0.0" upper="0.5"/>
    <dynamics damping="0.1" friction="0.1"/>
  </joint>

  <xacro:block name="camera_link" length="0.05"
      width="0.04" height="0.03" mass="0.1"/>
  <joint name="camera_joint" type="fixed">
    <parent link="camera_mast"/>
    <child link="camera_link"/>
    <origin xyz="0.0 0 0.0" rpy="0 0.6 0"/>
  </joint>

  <link name="camera_link_optical"/>
  <!-- generate an optical frame http://www.ros.org/reps/rep-0103.html#suffix-frames
      so that ros and opencv can operate on the camera frame correctly -->
  <joint name="camera_optical_joint" type="fixed">
    <!-- these values have to be these values otherwise the gazebo camera image
        won't be aligned properly with the frame it is supposedly originating from -->
    <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
    <parent link="camera_link"/>
    <child link="camera_link_optical"/>
  </joint>
  </xacro:if>

  <xacro:block name="sonar_link" length="0.015"
      width="0.05" height="0.02" mass="0.1"/>
  <joint name="sonar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="sonar_link"/>
    <origin xyz="0.05 0 0.05" rpy="0 -0.1 0"/>
  </joint>

</robot>
