<?xml version="1.0"?>
<robot name="popcanbot" xmlns:xacro="http://wiki.ros.org/xacro">

<xacro:property name="car_length" value="0.609"/>
<xacro:property name="car_width" value="0.5"/>
<xacro:property name="car_height" value="0.05"/>
<xacro:property name="clearance" value="0.10"/>
<xacro:property name="wheel_width" value="0.025"/>
<xacro:property name="wheel_radius" value="0.07"/>
<xacro:property name="caster_wheel_radius" value="0.04"/>
<xacro:property name="use_camera" value="false"/>
<!-- TODO(lwalter) pass these in as args -->

<xacro:include filename="$(find popcanbot_description)/urdf/popcanbot.gazebo"/>

<!-- don't use macro names that are the same as other key names
  like 'box', 'cylinder', etc. otherwise get Invalid parameter "size"
-->
<xacro:macro name="block" params="name length width height mass
    x:=0 y:=0 z:=0 r:=0.5 b:=0.5 g:=0.5">
  <link name="${name}">
     <visual>
      <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
      <geometry>
        <box size="${length} ${width} ${height}"/>
      </geometry>
      <material name="${name}_gray">
        <color rgba="${r} ${g} ${b} 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
      <geometry>
        <box size="${length} ${width} ${height}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
          ixx="${mass / 12.0 * (width * width + height * height)}" ixy="0.0" ixz="0.0"
          iyy="${mass / 12.0 * (length * length + height * height)}" iyz="0.0"
          izz="${mass / 12.0 * (length * length + width * width)}" />
    </inertial>
  </link>
</xacro:macro>

<!-- a wheel that rotates around the y axis, rolls forward toward the x axis -->
<!--origin xyz="${length/2} ${width/2} ${height/2}" /-->
<xacro:macro name="wheel" params="name width radius mass">
  <link name="${name}">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
      <geometry>
        <cylinder length="${width}" radius="${radius}"/>
      </geometry>
      <material name="${name}_black">
        <color rgba="0.2 0.2 0.2 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
      <geometry>
        <cylinder length="${width}" radius="${radius}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
      <mass value="${mass}"/>
      <inertia
          ixx="${mass / 12.0 * (3 * radius * radius + width * width)}" ixy="0.0" ixz="0.0"
          iyy="${mass / 12.0 * (3 * radius * radius + width * width)}" iyz="0.0"
          izz="${mass / 2.0 * (radius * radius)}"/>
    </inertial>
  </link>
</xacro:macro>

<xacro:macro name="generic_wheel" params="name parent radius width
    z:=0 y:=0 y_axis:=1 mass:=0.2 use_tran:=true">

  <xacro:wheel name="${name}" width="${width}" radius="${radius}" mass="${mass}"/>
  <joint name="${name}_joint" type="continuous">
    <parent link="${parent}"/>
    <child link="${name}"/>
    <origin xyz="0 ${y} ${z}" rpy="0 0 0"/>
    <axis xyz="0 ${y_axis} 0"/>
    <limit effort="100.0" velocity="0.5"/>
  </joint>

  <xacro:if value="${use_tran}">
  <transmission name="${name}_tran">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="${name}_joint">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="${name}_motor">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  </xacro:if>

  <gazebo reference="wheel_${name}">
    <mu1>800</mu1>
    <mu2>100</mu2>
    <kp value="10000000.0"/>
    <kd value="1.0"/>
  </gazebo>
</xacro:macro>  <!-- generic wheel -->

  <link name="base_link"/>
  <xacro:block name="chassis_link" length="${car_length}"
      width="${car_width}" height="${car_height}" mass="10.0"
      r="0.8" g="0.7" b="0.1"/>
  <joint name="chassis_joint" type="fixed">
    <parent link="base_link"/>
    <child link="chassis_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <!-- every link has to have inertia in order for it to work in gazebo
    even if it just connects two inertia links- without it the child link
    that doesn't have inertia won't appear.
    -->
  <xacro:block name="caster_block" length="${0.03}"
      width="${0.03}" height="${0.03}" mass="0.1"/>
  <joint name="caster_joint" type="continuous">
    <parent link="base_link"/>
    <child link="caster_block"/>
    <axis xyz="0 0 1"/>
    <origin xyz="${-car_length/2 + 0.1} 0 ${-car_height/2}" rpy="0 0 0"/>
  </joint>
  <xacro:generic_wheel name="wheel_caster" parent="caster_block"
      width="${wheel_width}"
      radius="${caster_wheel_radius}" mass="0.1" use_tran="false"
      z="${-(clearance - caster_wheel_radius)}"/>

  <xacro:block name="main_axle" length="${car_width/8.0}"
      width="${car_width + 0.05}" height="${car_width/8.0}" mass="0.1"
      />
  <joint name="main_axle_joint" type="fixed">
    <parent link="base_link"/>
    <child link="main_axle"/>
    <origin xyz="${car_length/2 - 0.1} 0 ${-(car_height/2 + clearance - wheel_radius)}"
        rpy="0 0 0"/>
  </joint>

  <xacro:generic_wheel name="wheel_front_left" parent="main_axle"
      y="${car_width/2 + wheel_width/2 + 0.02}"
      width="${wheel_width}" radius="${wheel_radius}"/>
  <xacro:generic_wheel name="wheel_front_right" parent="main_axle"
      y="${-1 * (car_width/2 + wheel_width/2 + 0.02)}"
      width="${wheel_width}" radius="${wheel_radius}"
      y_axis="1"/>

  <!-- the arm -->
  <xacro:block name="arm_vertical" length="0.05"
      width="0.05" height="0.5" mass="1.0" z="0.25"/>
  <joint name="arm_vertical_rotary_joint" type="revolute">
    <parent link="base_link"/>
    <child link="arm_vertical"/>
    <origin xyz="0 0 ${car_height/4}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="100.0" upper="1.6" lower="-1.6" velocity="0.5"/>
  </joint>

  <transmission name="arm_vertical_rotary_tran">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="arm_vertical_rotary_joint">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="arm_vertical_rotary_motor">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <xacro:block name="arm_vertical_platform" length="0.05"
      width="0.1" height="0.05" mass="0.1"
      r="0.8" g="0.8" b="0.8"/>
  <joint name="arm_vertical_platform_joint" type="prismatic">
    <parent link="arm_vertical"/>
    <child link="arm_vertical_platform"/>
    <origin xyz="0.05 0 0.25" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="20.0" velocity="0.25" lower="-0.14" upper="0.20"/>
  </joint>
  <transmission name="arm_vertical_rotary_tran">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="arm_vertical_platform_joint">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="arm_vertical_platform_motor">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <xacro:block name="arm_horizontal" length="0.5"
      width="0.05" height="0.05" mass="0.2"/>
  <joint name="arm_horizontal_platform_joint" type="prismatic">
    <parent link="arm_vertical_platform"/>
    <child link="arm_horizontal"/>
    <origin xyz="0.1 -0.06 -0.05" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit effort="20.0" velocity="0.25" lower="-0.22" upper="0.05"/>
  </joint>
  <transmission name="arm_vertical_rotary_tran">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="arm_horizontal_platform_joint">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="arm_horizontal_platform_motor">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <!-- gripper -->
  <xacro:block name="gripper_left" length="0.07"
      width="0.02" height="0.02" mass="0.05" r="0.1" b="0.1" g="0.6" x="0.03"/>
  <joint name="gripper_left_joint" type="revolute">
    <parent link="arm_horizontal"/>
    <child link="gripper_left"/>
    <origin xyz="0.25 0.02 -0.05" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="100.0" upper="0.4" lower="-0.1" velocity="0.5"/>
  </joint>
  <xacro:block name="gripper_left_tip" length="0.07"
      width="0.02" height="0.02" mass="0.05" r="0.1" b="0.1" g="0.6" x="0.03"/>
  <joint name="gripper_left_tip_joint" type="fixed">
    <parent link="gripper_left"/>
    <child link="gripper_left_tip"/>
    <origin xyz="0.05 0.0 0.0" rpy="0 0 -0.3"/>
  </joint>

  <xacro:block name="gripper_right" length="0.07"
      width="0.02" height="0.02" mass="0.05" r="0.1" b="0.1" g="0.6" x="0.03"/>
  <joint name="gripper_right_joint" type="revolute">
    <parent link="arm_horizontal"/>
    <child link="gripper_right"/>
    <origin xyz="0.25 -0.02 -0.05" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="100.0" upper="0.1" lower="-0.4" velocity="0.5"/>
  </joint>
  <xacro:block name="gripper_right_tip" length="0.07"
      width="0.02" height="0.02" mass="0.05" r="0.1" b="0.1" g="0.6" x="0.03"/>
  <joint name="gripper_right_tip_joint" type="fixed">
    <parent link="gripper_right"/>
    <child link="gripper_right_tip"/>
    <origin xyz="0.05 0.0 0.0" rpy="0 0 0.3"/>
  </joint>


  <!-- sensors -->
  <xacro:if value="${use_camera}">
  <xacro:block name="camera_mast" length="0.04"
      width="0.02" height="0.03" mass="0.1"/>
  <joint name="camera_mast_joint" type="prismatic">
    <parent link="base_link"/>
    <child link="camera_mast"/>
    <origin xyz="0.1 0 0.4" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="20.0" velocity="0.25" lower="0.0" upper="0.5"/>
  </joint>

  <xacro:block name="camera_link" length="0.05"
      width="0.04" height="0.03" mass="0.1"/>
  <joint name="camera_joint" type="fixed">
    <parent link="camera_mast"/>
    <child link="camera_link"/>
    <origin xyz="0.0 0 0.0" rpy="0 0.4 0"/>
  </joint>

  <link name="camera_link_optical"/>
  <!-- generate an optical frame http://www.ros.org/reps/rep-0103.html#suffix-frames
      so that ros and opencv can operate on the camera frame correctly -->
  <joint name="camera_optical_joint" type="fixed">
    <!-- these values have to be these values otherwise the gazebo camera image
        won't be aligned properly with the frame it is supposedly originating from -->
    <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
    <parent link="camera_link"/>
    <child link="camera_link_optical"/>
  </joint>
  </xacro:if>

</robot>
