<?xml version="1.0"?>
<robot name="util" xmlns:xacro="http://wiki.ros.org/xacro">

<!-- don't use macro names that are the same as other key names
  like 'box', 'cylinder', etc. otherwise get Invalid parameter "size"
-->
<xacro:macro name="block" params="name length width height mass
    x:=0 y:=0 z:=0
    r:=0.5 b:=0.5 g:=0.5
    mu:=0.0 kp:=1000.0 kd:=1.0">
  <link name="${name}">
     <visual>
      <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
      <geometry>
        <box size="${length} ${width} ${height}"/>
      </geometry>
      <material name="${name}_gray">
        <color rgba="${r} ${g} ${b} 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
      <geometry>
        <box size="${length} ${width} ${height}"/>
      </geometry>
      <contact_coefficients mu="${mu}" kp="${kp}" kd="${kd}"/>
    </collision>
    <inertial>
      <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
          ixx="${mass / 12.0 * (width * width + height * height)}" ixy="0.0" ixz="0.0"
          iyy="${mass / 12.0 * (length * length + height * height)}" iyz="0.0"
          izz="${mass / 12.0 * (length * length + width * width)}" />
    </inertial>
  </link>
</xacro:macro>

<!-- a wheel that rotates around the y axis, rolls forward toward the x axis -->
<!--origin xyz="${length/2} ${width/2} ${height/2}" /-->
<xacro:macro name="wheel" params="name width radius mass
    r:=0.5 b:=0.5 g:=0.5
    mu:=0.0 kp:=1000.0 kd:=1.0">
  <link name="${name}">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
      <geometry>
        <cylinder length="${width}" radius="${radius}"/>
      </geometry>
      <material name="${name}_black">
        <color rgba="${r} ${g} ${b} 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
      <geometry>
        <cylinder length="${width}" radius="${radius}"/>
      </geometry>
      <contact_coefficients mu="${mu}" kp="${kp}" kd="${kd}"/>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
      <mass value="${mass}"/>
      <inertia
          ixx="${mass / 12.0 * (3 * radius * radius + width * width)}" ixy="0.0" ixz="0.0"
          iyy="${mass / 12.0 * (3 * radius * radius + width * width)}" iyz="0.0"
          izz="${mass / 2.0 * (radius * radius)}"/>
    </inertial>
  </link>
  <gazebo reference="${name}">
    <!-- this doesn't work, how to specify rgb color for gazebo? -->
    <!--color rgba="${r} ${g} ${b} 1.0"/-->
  </gazebo>
</xacro:macro>

<xacro:macro name="generic_wheel" params="name parent radius width
    x:=0 y:=0 z:=0
    r:=0.6 g:=0.6 b:=0.6
    y_axis:=1 mass:=0.2 use_tran:=true
    mu1:=200 mu2:=100">

  <xacro:wheel name="${name}" width="${width}" radius="${radius}" mass="${mass}"
      r="1.0" g="1.0" b="1.0"/>
  <joint name="${name}_joint" type="continuous">
    <parent link="${parent}"/>
    <child link="${name}"/>
    <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
    <axis xyz="0 ${y_axis} 0"/>
    <limit effort="100.0" velocity="0.5"/>
  </joint>

  <xacro:if value="${use_tran}">
  <transmission name="${name}_tran">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="${name}_joint">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="${name}_motor">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  </xacro:if>

  <gazebo reference="${name}">
    <mu1>${mu1}</mu1>
    <mu2>${mu2}</mu2>
    <kp value="10000000.0"/>
    <kd value="1.0"/>
  </gazebo>
</xacro:macro>  <!-- generic wheel -->

</robot>
