popcanbot:
  # these controller will be loaded as gazebo plugins, so the /gazebo
  # node will be in control of them.
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  front_left:
    wheel_position_controller:
      # TODO(lucasw) are these better off velocity controllers?
      # Tried that and they spin by themselves
      type: effort_controllers/JointPositionController
      joint: wheel_front_left_joint
      pid: {p: 20.0, i: 0.001, d: 1.0, i_clamp_min: -1.0, i_clamp_max: 1.0}
  front_right:
    wheel_position_controller:
      type: effort_controllers/JointPositionController
      joint: wheel_front_right_joint
      pid: {p: 20.0, i: 0.001, d: 1.0, i_clamp_min: -1.0, i_clamp_max: 1.0}
