popcanbot:
  # these controller will be loaded as gazebo plugins, so the /gazebo
  # node will be in control of them.
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  front_left:
    wheel_position_controller:
      # TODO(lucasw) are these better off velocity controllers?
      # Tried that and they spin by themselves
      type: effort_controllers/JointPositionController
      joint: wheel_front_left_joint
      pid: {p: 20.0, i: 0.001, d: 1.0, i_clamp_min: -1.0, i_clamp_max: 1.0}
  front_right:
    wheel_position_controller:
      type: effort_controllers/JointPositionController
      joint: wheel_front_right_joint
      pid: {p: 20.0, i: 0.001, d: 1.0, i_clamp_min: -1.0, i_clamp_max: 1.0}
  arm:
    arm_vertical_rotation_controller:
      type: effort_controllers/JointPositionController
      joint: arm_vertical_rotary_joint
      pid: {p: 0.5, i: 0.001, d: 0.05, i_clamp_min: -1.0, i_clamp_max: 1.0}
    arm_vertical_position_controller:
      type: effort_controllers/JointPositionController
      joint: arm_vertical_platform_joint
      pid: {p: 50.0, i: 0.001, d: 1.0, i_clamp_min: -10.0, i_clamp_max: 10.0}
    arm_horizontal_position_controller:
      type: effort_controllers/JointPositionController
      joint: arm_horizontal_platform_joint
      pid: {p: 1.0, i: 0.001, d: 0.5, i_clamp_min: -1.0, i_clamp_max: 1.0}
    gripper_left_position_controller:
      type: effort_controllers/JointPositionController
      joint: gripper_left_joint
      pid: {p: 0.3, i: 0.001, d: 0.05, i_clamp_min: -1.0, i_clamp_max: 1.0}
    gripper_right_position_controller:
      type: effort_controllers/JointPositionController
      joint: gripper_right_joint
      pid: {p: 0.3, i: 0.001, d: 0.05, i_clamp_min: -1.0, i_clamp_max: 1.0}
