axis_linear: 4  # Left thumb stick vertical
scale_linear: 0.35
scale_linear_turbo: 0.7

axis_angular: 0  # Left thumb stick horizontal
scale_angular: 0.17

enable_button: 4  # Left trigger button
enable_turbo_button: 5  # Right trigger button
